---
- hosts: all
  gather_facts: False
  tasks:
    - name: Install python 2
      become: yes
      raw: command -v /usr/bin/python || { apt -y update && apt install -y python-minimal && echo "Installed python"; }
      register: result
      changed_when: "'Installed python' in result.stdout_lines"
- hosts: all
  tasks:
    - name: Log
      debug:
        msg: "networks: {{ networks }}"
    - name: Update
      become: yes
      apt:
        autoclean: yes
        autoremove: yes
        upgrade: dist
        update_cache: yes
      when: "no_update is not defined"
    - name: Install requirements
      become: yes
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - imagemagick
        - ntpdate
        - wondershaper
    - name: Configure WiFi
      become: yes
      template:
        src: "files/{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: "wpa_supplicant.conf", dest: "/etc/wpa_supplicant/wpa_supplicant.conf" }
        - { src: "wlan0", dest: "/etc/network/interfaces.d/wlan0" }
    - name: Configure SSH
      become: yes
      template:
        src: files/sshd_config
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        validate: /usr/sbin/sshd -t -f %s
    - name: Copy core scripts
      become: yes
      copy:
        src: "files/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        owner: root
        group: root
        mode: '0755'
      loop:
        - instapic.sh
        - ipgetter.sh
        - timedate.sh
        - wifireconnect.sh
    - name: Copy timedate service
      become: yes
      copy:
        src: "files/timedate.service"
        dest: "/etc/systemd/system/timedate.service"
        owner: root
        group: root
        mode: '0755'
    - name: Enable services
      become: yes
      systemd:
        name: "{{ item }}"
        daemon_reload: yes
        enabled: yes
      loop:
        - ssh
        - timedate
    - name: Remove extra cron lines
      become: yes
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/cron.daily/apt-compat
        - /etc/cron.daily/aptitude
        - /etc/cron.daily/bsdmainutils
        - /etc/cron.daily/dpkg
        - /etc/cron.daily/man-db
        - /etc/cron.weekly/man-db
    - name: Enable raspi camera
      become: yes
      lineinfile:
        path: /boot/config.txt
        line: "{{ item }}"
      loop:
        - gpu_mem=128
        - start_x=1
    - name: Enable camera service
      cron:
        name: "Take pictures"
        job: instapic.sh
    - name: Disable extra services
      become: yes
      systemd:
        name: "{{ item }}"
        enabled: no
      loop:
        - apt-daily-upgrade.timer
        - systemd-timesyncd
        - avahi-daemon
        - bluetooth
    - name: Create mountpoint
      file:
        path: /home/pi/Documents
        state: directory
    - name: Ensure mountpoint exists
      become: yes
      lineinfile:
        path: /etc/fstab
        regexp: '^/dev/sda1\s+/home/pi/Documents.*'
        line: "/dev/sda1 /home/pi/Documents vfat nofail,noatime,user,rw,uid=1000,gid=0 0 2"
    - name: Reboot
      become: yes
      reboot:
